### ISSUE TITLE
Dataset Latinoamérica

### ISSUE THREAD

**Issue by ZurMaD** [agustincordes/COVIDLatam#1]
Hola, vi que estás haciendo un seguimiento a nivel latinoamérica.
Tenemos[ este repositorio](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica) en el que estamos queriendo centralizar la información con resolución de subdivisión de cada país y quizás pueda interesarte.
La data la tenemos actualizada según una tabla en nuestro README, porfavor revisar ya que hay países que aún no reportan cifras. También tenemos un dashboard.

**Comment by agustincordes** [comment]
Uy, genial! Gracias por ponerte en contacto, ahí miro la repo. Estoy tratando de automatizar datos haciendo un scrapping de Worldometer, pero me encuentro con que la data no es muy consistente. Me sumo al Slack así unimos esfuerzos.

**Comment by ZurMaD** [comment]
Perfecto!
